name: CI

on:
  # Run on pushes to the default branch.
  push:
    branches:
      - main

  # Run on all PRs.
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  # Support merge queues.
  merge_group:

  # Allow running this workflow manually from the Actions tab.
  workflow_dispatch:

permissions: {}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Setup Turborepo cache
        uses: rharkor/caching-for-turbo@56219402aacc0d06b650d898c222996dbc1191ec # v2.3.14

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Merge checks
        run: bun run turbo build check-types lint format:check

      - name: Prepare StackBlitz demo template
        run: |
          cp -R apps/demo .pkg-pr-new-demo-template
          cp tsconfig.base.json .pkg-pr-new-demo-template/tsconfig.base.json
          sed -i 's#\.\./\.\./tsconfig\.base\.json#./tsconfig.base.json#' .pkg-pr-new-demo-template/tsconfig.json

      - name: Publish to pkg.pr.new
        run: bunx pkg-pr-new publish 'packages/*' --template '.pkg-pr-new-demo-template'
